---
- name: Install open-vm-tools
  become: true
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - open-vm-tools
    - open-vm-tools-desktop

- name: Mount hgfs shared folders
  become: true
  mount:
    fstype: fuse.vmhgfs-fuse
    path: /mnt/hgfs
    src: .host:/
    state: mounted
    opts: allow_other

  #- name: Mount hgfs shared folders
  #  become: true
  #  command: mount -t fuse.vmhgfs-fuse .host:/ /mnt/hgfs -o allow_other
  #
  #- name: Add mount to fstab
  #  become: true
  #  lineinfile:
  #    path: /etc/fstab
  #    regexp: 'vmhgfs-fuse'
  #    line: '.host:/ /mnt/hgfs fuse.vmhgfs-fuse allow_other 0 0'
